### ISSUE TITLE
pod 安装不了

### ISSUE THREAD

**Issue by OnlyThen** [Allen0828/AEAlertView#1]
你好，我这里使用清华大学cocoapod源，然后安装不了你这个库。

**Comment by OnlyThen** [comment]
环境出问题了，已解决。

**Comment by Allen0828** [comment]
加我v 15850057960发自我的iPhone------------------ 原始邮件 ------------------发件人: Zhang Yu  <notifications@github.com>发送时间: 2019年7月5日 18:08收件人: Allen0828/AEAlertView <AEAlertView@noreply.github.com>抄送: Subscribed <subscribed@noreply.github.com>主题: 回复：[Allen0828/AEAlertView] pod 安装不了 (#1)你好，我这里使用清华大学cocoapod源，然后安装不了你这个库。

—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or mute the thread.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/Allen0828/AEAlertView/issues/1?email_source=notifications\u0026email_token=AE5LTILVH3VRHU4EEXF23BTP54MRHA5CNFSM4H6J5C3KYY3PNVWWK3TUL52HS4DFUVEXG43VMWVGG33NNVSW45C7NFSM4G5QXQZA",
"url": "https://github.com/Allen0828/AEAlertView/issues/1?email_source=notifications\u0026email_token=AE5LTILVH3VRHU4EEXF23BTP54MRHA5CNFSM4H6J5C3KYY3PNVWWK3TUL52HS4DFUVEXG43VMWVGG33NNVSW45C7NFSM4G5QXQZA",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]
